# baseURL = "https://richonrails.social/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Rich On Rails"
copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Rich On Rails"
  headline = "Just a normal train nerd"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
    # { email = "mailto:hello@your_domain.com" },
    { link = { href = "https://richonrails.blog/", text = "The Blog"} },
    { link = { href = "https://richonrails.show", text = "Podcast" } },
    { link = { href = "https://richonrails.photos/", text = "Photo Blog" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    { facebook = "https://facebook.com/richonrailsblog" },
    { flickr = "https://www.flickr.com/people/shotbyrich/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
     { instagram = "https://instagram.com/richonrails" },
     { link = { href = "https://pixelfed.social/richonrails", text = "Pixelfed" } },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
     { mastodon = "https://mastodon.social/@richonrails" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    { tiktok = "https://tiktok.com/@richonrails" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/richonrails" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/@rich_on_rails" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
